FROM maven:3-eclipse-temurin-21-alpine as maven

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

WORKDIR /usr/src/app

COPY --from=maven /app/target/backend-*.jar backend.jar

CMD ["java","-jar","backend.jar"]

EXPOSE 8080